
-- Create storage bucket for reports
INSERT INTO storage.buckets (id, name, public) VALUES ('reports', 'reports', false)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to read report files
CREATE POLICY "Authenticated can read reports"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'reports');

-- Allow service-role (edge functions) and authenticated to upload
CREATE POLICY "Authenticated can upload reports"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'reports');

CREATE POLICY "Authenticated can update reports"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'reports');

-- Sample supplier
INSERT INTO public.suppliers (id, company_name, ico, country, address, city, sector, website_url, notes)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Acme Corp s.r.o.',
  '12345678',
  'CZ',
  'Wenceslas Square 1',
  'Prague',
  'Technology',
  'https://acme.example.com',
  'Sample supplier for testing'
) ON CONFLICT (id) DO NOTHING;

-- Sample completed evaluation
INSERT INTO public.evaluations (id, supplier_id, status, overall_score, overall_risk_level, executive_summary, completed_at)
VALUES (
  '22222222-2222-2222-2222-222222222222',
  '11111111-1111-1111-1111-111111111111',
  'completed',
  72,
  'MEDIUM',
  'Acme Corp presents a moderate risk profile. Financial health is solid with steady revenue growth. Minor GDPR compliance gaps were noted. No sanctions matches found across EU, OFAC, and UN lists. Overall, the supplier is suitable for engagement with recommended compliance improvements.',
  now()
) ON CONFLICT (id) DO NOTHING;

-- Sample evaluation modules
INSERT INTO public.evaluation_modules (evaluation_id, module_type, status, score, risk_level, summary, findings, completed_at)
VALUES
  ('22222222-2222-2222-2222-222222222222', 'financial', 'completed', 80, 'LOW', 'Solid financial health with stable cash flow', '["Revenue growth 4.1% YoY","Debt-to-equity ratio healthy at 0.35","No insolvency proceedings found","Credit rating: BBB+"]', now()),
  ('22222222-2222-2222-2222-222222222222', 'compliance', 'completed', 65, 'MEDIUM', 'Minor gaps in GDPR compliance identified', '["GDPR compliance partially implemented","All required business licenses current","1 pending regulatory review for Q2 2026"]', now()),
  ('22222222-2222-2222-2222-222222222222', 'sanctions', 'completed', 98, 'LOW', 'No matches on any sanction lists', '["Clear on EU consolidated sanctions list","Clear on OFAC SDN list","Clear on UN Security Council list"]', now())
ON CONFLICT DO NOTHING;

-- Sample report record (file_url null — will be generated by edge function)
INSERT INTO public.reports (id, evaluation_id, file_url)
VALUES ('33333333-3333-3333-3333-333333333333', '22222222-2222-2222-2222-222222222222', null)
ON CONFLICT (id) DO NOTHING;
