-- Migration: Add per-source AI summaries to firecrawl scrape runs
-- Stores a JSONB map of { source_name: summary_text } generated by gpt-4o-mini
-- after each evaluation scrape.

ALTER TABLE firecrawl_scrape_runs
  ADD COLUMN source_summaries JSONB DEFAULT '{}';
